import * as github from '@actions/github'
import * as core from '@actions/core'
import * as fs from 'fs'
import * as path from 'path'
import { DraftResult } from './drafter'

type Octokit = ReturnType<typeof github.getOctokit>

export async function applyDraftAndOpenPR(
  octokit: Octokit,
  owner: string,
  repo: string,
  prNumber: number,
  prBranch: string,
  drafts: DraftResult[]
): Promise<void> {
  const draftBranch: string = `watchdocs/draft-${prNumber}`

  // create new branch from the PR branch
  const { data: ref } = await octokit.rest.git.getRef({
    owner,
    repo,
    ref: `heads/${prBranch}`,
  })

  const sha: string = ref.object.sha

  await octokit.rest.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${draftBranch}`,
    sha,
  })

  core.info(`Created branch ${draftBranch} from ${prBranch}`)

  // apply additions to each doc file
  for (const draft of drafts) {
    const filePath: string = path.join(process.cwd(), draft.filePath)
    const existing: string = fs.existsSync(filePath)
      ? fs.readFileSync(filePath, 'utf-8')
      : ''

    const updated: string = `${existing}\n\n${draft.additions}`

    // get current file SHA for update
    const { data: fileData } = await octokit.rest.repos.getContent({
      owner,
      repo,
      path: draft.filePath.replace(/^\//, ''),
      ref: draftBranch,
    })

    const fileSha: string = Array.isArray(fileData) ? '' : fileData.sha

    await octokit.rest.repos.createOrUpdateFileContents({
      owner,
      repo,
      path: draft.filePath.replace(/^\//, ''),
      message: `docs: WatchDocs draft additions for PR #${prNumber}`,
      content: Buffer.from(updated).toString('base64'),
      sha: fileSha,
      branch: draftBranch,
    })

    core.info(`Applied draft additions to ${draft.filePath}`)
  }

  // open PR targeting the original PR branch
  const { data: pr } = await octokit.rest.pulls.create({
    owner,
    repo,
    title: `docs: WatchDocs draft additions for PR #${prNumber}`,
    body: `This PR was automatically generated by WatchDocs.\n\nIt contains draft documentation additions for the gaps identified in PR #${prNumber}.\n\nReview and merge into your docs branch when ready.`,
    head: draftBranch,
    base: prBranch,
  })

  core.info(`Opened draft PR: ${pr.html_url}`)
}